openapi: 3.2.0
info:
  version: 1.2.3
  title: Fleet API Specifications Vehicle assignments API
  x-logo:
    url: logo.svg
  description: '# Introduction

    The Avrios Fleet-API allows syncing fleet data with our system.'
servers:
- url: https://api.avrios.com
tags:
- name: Vehicle assignments
paths:
  /v1/vehicles/{uuid}/assignments:
    get:
      tags:
      - Vehicle assignments
      summary: GET vehicle assignments
      description: Get all driver assignments of a specific vehicle.
      operationId: findVehicleAssignments
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: limit
        in: query
        description: Number of items in a page
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
      - name: pageNumber
        in: query
        description: Number of the page
        required: false
        schema:
          type: integer
          minimum: 1
      - name: sortBy
        in: query
        description: Sorting key
        required: false
        schema:
          type: string
          enum:
          - uuid
          - vehicleUuid
          - driverUuid
          - duration_startDate
          - duration_endDate
          - active
      - name: reverse
        in: query
        description: Sorting order
        required: false
        schema:
          type: boolean
          enum:
          - 'false'
          - 'true'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPageAssignmentDto'
        '400':
          description: Bad request - information on the invalid fields will be provided in the response body
        '404':
          description: Vehicle not found.
    post:
      tags:
      - Vehicle assignments
      summary: ASSIGN a specified driver to this vehicle
      description: Assign a driver (specified in the request body) to the vehicle under this url.
      operationId: createVehicleAssignment
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentDto'
        '400':
          description: Bad request - information on the invalid fields will be provided in the response body
        '404':
          description: Vehicle or driver not found.
        '409':
          description: The new assignment conflicts with one or more other assignments. The conflicting assignments will be returned in an error response.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAssignmentByVehicleRequest'
  /v1/vehicles/{uuid}/assignments/query:
    post:
      tags:
      - Vehicle assignments
      summary: QUERY vehicle assignments
      description: Query driver assignments of a specific vehicle.
      operationId: queryVehicleAssignments
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: limit
        in: query
        description: Number of items in a page
        required: false
        schema:
          type: integer
          maximum: 100
          minimum: 1
      - name: pageNumber
        in: query
        description: Number of the page
        required: false
        schema:
          type: integer
          minimum: 1
      - name: sortBy
        in: query
        description: Sorting key
        required: false
        schema:
          type: string
          enum:
          - uuid
          - vehicleUuid
          - driverUuid
          - duration_startDate
          - duration_endDate
          - active
      - name: reverse
        in: query
        description: Sorting order
        required: false
        schema:
          type: boolean
          enum:
          - 'false'
          - 'true'
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiPageAssignmentDto'
        '400':
          description: Bad request - information on the invalid fields will be provided in the response body
        '404':
          description: Vehicle not found.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VehicleAssignmentQueryApiParams'
  /v1/vehicles/{uuid}/assignments/{assignmentUuid}:
    delete:
      tags:
      - Vehicle assignments
      summary: DELETE vehicle assignment
      description: Delete driver to vehicle assignment identified by uuid path parameter.
      operationId: deleteVehicleAssignment
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: assignmentUuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Void'
        '204':
          description: Successful operation - no content is expected.
        '400':
          description: Bad request - information on the invalid fields will be provided in the response body
        '404':
          description: Vehicle not found or this assignment was not found for this vehicle.
  /v1/vehicles/{uuid}/assignments/{assignmentUuid}/duration:
    post:
      tags:
      - Vehicle assignments
      summary: UPDATE the duration of an existing assignment
      description: Change the timing of a specific assignment. Body is a map of fields to update.
      operationId: updateVehicleAssignment
      parameters:
      - name: uuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      - name: assignmentUuid
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssignmentDto'
        '400':
          description: Bad request - information on the invalid fields will be provided in the response body
        '404':
          description: Vehicle or assignment not found.
        '409':
          description: The new assignment timing conflicts with one or multiple ones. The conflicting assignments will be returned in an error response.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DurationUpdateApiParams'
components:
  schemas:
    DurationDto:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Void:
      type: object
    DurationUpdateApiParams:
      type: object
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type:
          - string
          - 'null'
          format: date-time
    ApiPageInformation:
      type: object
      properties:
        pageNumber:
          type: integer
          format: int32
        limit:
          type: integer
          format: int32
    AssignmentDto:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        vehicleUuid:
          type: string
          format: uuid
        driverUuid:
          type: string
          format: uuid
        duration:
          $ref: '#/components/schemas/DurationDto'
        active:
          type: boolean
    CreateAssignmentByVehicleRequest:
      type: object
      properties:
        driverUuid:
          type: string
          format: uuid
        duration:
          $ref: '#/components/schemas/DurationDto'
    ApiPageAssignmentDto:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/AssignmentDto'
        page:
          $ref: '#/components/schemas/ApiPageInformation'
        totalItems:
          type: integer
          format: int64
    InstantRangeApiParams:
      type: object
      properties:
        atOrAfter:
          type: string
          format: date-time
        before:
          type: string
          format: date-time
    VehicleAssignmentQueryApiParams:
      type: object
      properties:
        driverUuid:
          type: string
          format: uuid
        when:
          description: Date range assignments active within. Cannot have a value when `starting` or `ending` have a value.
          $ref: '#/components/schemas/InstantRangeApiParams'
        starting:
          $ref: '#/components/schemas/InstantRangeApiParams'
        ending:
          $ref: '#/components/schemas/InstantRangeApiParams'
x-tagGroups:
- name: Vehicles
  tags:
  - Vehicles
  - Vehicle license plates
  - Vehicle assignments
  - Vehicle usages
  - Vehicle custom fields
  - Vehicle financing
- name: Drivers
  tags:
  - Drivers
  - Driver assignments
  - Driver custom fields
- name: Other
  tags:
  - Custom fields
  - Invoices
  - Organizations
